- name: nexus3
  hosts: nexus3
  remote_user: centos
  become: true

  vars:
    nexus_version: '3.30.0-01'
    # nexus_version: '3.32.0-03'
    # nexus_upgrade: true

  roles:
    - geerlingguy.java
    - ansible-thoteam.nexus3-oss
